---
# defaults file for zabbix_v3_lts

zabbix_repo_url: "http://repo.zabbix.com/zabbix/3.0/rhel/7/$basearch/"
zabbix_repo_enable: yes
zabbix_repo_gpgcheck: 1
zabbix_repo_gpg_url: ""
zabbix_yum_packages:
    - libselinux-python
    - zabbix-server-pgsql
    - zabbix-web-pgsql
    - zabbix-agent
    - zabbix-java-gateway
    - python-pyzabbix
    - nginx
zabbix_php_packages:
    - php
    - php-cli
    - php-common
    - php-devel
    - php-pear
    - php-gd
    - php-fpm
    - php-mbstring
    - php-ldap
    - php-pgsql
    - php-xml
# Users
zabbix_web_user: nginx
zabbix_web_group: nginx
# Package
zabbix_web_package: zabbix-web-pgsql
# Web directories
zabbix_web_conf_dir:   /etc/zabbix
zabbix_web_log_dir:    /var/log/zabbix-web
zabbix_web_home_dir:   /var/www/zabbix
zabbix_web_public_dir: /usr/share/zabbix
# Server host
zabbix_server_host: hassdvmona03
zabbix_server_port: 10051
# More server details
zabbix_web_fqdn: hassdvmona03.dev2.cloud.local
logstash_conf_dir: /etc/logstash/conf.d
php_fpm_conf_dir: /etc/php-fpm.d/

zabbix_web_fastcgi_params: fastcgi_params
