# Elasticsearch default vars

# Environment settings
golden_image_used: false
elasticsearch_cluster: false

# General role settings
elasticsearch_path_data_dir: /opt/data/elasticsearch/data
elasticsearch_path_logs_dir: /opt/data/elasticsearch/logs
elasticsearch_node_name: node-1
elasticsearch_cluster_name: elk_azure_cluster
elasticsearch_network_host: 127.0.0.1
elasticsearch_http_port: 9200

# Yum settings
elastic_yum_url: http://packages.elastic.co/elasticsearch/2.x/centos
elasic_yum_check: 1
elastic_yum_gpg: http://packages.elastic.co/GPG-KEY-elasticsearch
