# Elastic Beats default vars

logstash_server_ip: 127.0.0.1
logstash_server_port: 5044

# Yum repository settings
beats_yum_url: "https://packages.elastic.co/beats/yum/el/$basearch"
beats_yum_gpg: "https://packages.elastic.co/GPG-KEY-elasticsearch"
beats_yum_check: yes
beats_yum_pkg_to_install:
  - filebeat
  - topbeat
  - packetbeat

beats_agent_checker: "systemctl list-unit-files"

# filebeat specific settings

filebeat_prospect_input_type: log
filebeat_prospect_doc_type: syslog
filebeat_prospect_registry_file: /var/lib/filebeat/registry
filebeat_config_dir: /etc/filebeat
file_beat_bulk_max_size: 1024
file_beat_log_path: /var/log/mybeat
file_beat_log_name: filebeat.log
file_beat_keep_file: 7

# topbeat specific settings

topbeat_config_dir: /etc/topbeat
top_beat_bulk_max_size: 1024
top_beat_log_path: /var/log/mybeat
top_beat_log_name: topbeat.log
top_beat_keep_file: 7

# packetbeat specific settings

packetbeat_config_dir: /etc/packetbeat
packet_beat_bulk_max_size: 1024
packet_beat_log_path: /var/log/mybeat
packet_beat_log_name: packetbeat.log
packet_beat_keep_file: 7

# Certificates
upload_logstash_certificate: yes
logstash_cert_path: /etc/pki/tls/certs/logstash-forwarder.crt
logstash_pub_cert: |
  ----PLACE CERT HERE----
