---

# Deploy Zabbix agents
- hosts: all
  gather_facts: true
  become: yes
  roles:
    - { role: zabbix-agents, tags ["zabbix-agents"] }
  tags: zabbix-agents

# Deploy Beats/Logstash agents
- hosts: all
  gather_facts: true
  become: yes
  roles:
    - { role: logstash-agent, tags ["logstash-agent"] }
    - { role: beats-agent, tags ["beats-agent"] }
  tags: logstash-agents

# Zabbix database
- hosts: zabbix-db
  gather_facts: true
  become: yes
  roles:
    - { role: postgres, tags: ["postgres"] }
  tags: database

# Zabbix application
- hosts: zabbix-app
  gather_facts: true
  become: yes
  roles:
    - { role: java, tags: ["java"] }
    - { role: zabbix_v3, tags: ["zabbix"] }
  tags: zabbix


# REMEMBER TO RUN AS FOLLOWING
# ansible-playbook -i inventory/mgmt-layer site.yml -u user --ask-become-pass -k
