---
- name: Install kibana and Nginx
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - kibana
    - nginx

- name: Ensure kibana is started on boot
  service:
    name: kibana
    enabled: yes

- name: Ensure nginx is started on boot
  service:
    name: nginx
    enabled: yes
