---
# defaults file for ansible-logstash
clear_logstash_config: false  #defines if logstash_config_dir should be cleared out
logstash_config_dir: /etc/logstash/conf.d
logstash_base_configs:
  - 000_system_inputs
  - 101_messages
  - 999_outputs
logstash_system_file_inputs:
  - path: /var/log/messages
    type: messages
#logstash_basic_patterns_configs:
#  - postfix
#logstash_service_configs:
#  - 001_service_inputs
#  - 201_tomcat
#logstash_service_file_inputs:
#  - path: /usr/share/tomcat6/logs/catalina.out
#    type: tomcat
#logstash_patterns_configs:
#  - tomcat
logstash_folder: /opt/logstash
logstash_base_outputs:
  - output: redis
    output_host: '{{ logstash_server_ip }}'
logstash_project: project_name
logstash_log_dir: /var/log/logstash
logstash_server_ip: 127.0.0.1
logstash_version: 1.5
logstash_enabled: false
local_domain: 127.0.0.1
logstash_yum_url: "http://packages.elasticsearch.org/logstash/2.2/centos"
logstash_yum_gpg: "http://packages.elasticsearch.org/GPG-KEY-elasticsearch"
logstash_gpg_check: yes
