---

- name: Setup Logstash repo
  yum_repository:
    name: Logstash
    description: Logstash repo
    baseurl: "{{ logstash_yum_url }}"
    gpgcheck: yes
    gpgkey: "{{ logstash_yum_gpg }}"
    enabled: yes

- name: Installing logstash
  yum:
    name: logstash
    state: installed
    disable_gpg_check: "{{ logstash_gpg_check }}"

- name: Enabling logstash on boot and start
  service:
    name: logstash
    state: started
    enabled: yes
