---

zabbix_port: 10050
zabbix_user: zabbix
zabbix_group: zabbix
zabbix_agent_log_dir: /var/log/zabbix-agent
zabbix_master_ip: 127.0.0.1
zabbix_repo_url: "http://repo.zabbix.com/zabbix/3.0/rhel/7/$basearch/"
zabbix_repo_enable: yes
zabbix_repo_gpgcheck: 1
zabbix_repo_gpg_url: "http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX"
