---
- name: restart postgres
  service:
    name: "postgresql-{{ postgres_version_nr }}"
    state: restarted

- name: reload postgres
  service:
    name: "postgresql-{{ postgres_version_nr }}"
    state: reloaded
