---
#It works only with Ansible 2.0 that supports the header option in get_url.
#If using Ansible 2 use this task for its idempotency.

#- name: RedHat/Centos | Downloading Java 8 sdk (ansible 2.0)
#  get_url:
#    url: "{{ jre_url }}"
#    dest: /opt/
#    headers: "Cookie':' gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
#    validate_certs: no

- name: Downloading Java 8 sdk (ansible 2.0)
  command: >
    wget -q -O /opt/jdk-{{ jre_version }}-linux-x64.rpm --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" {{ jre_url }} creates=/opt/jdk-{{ jre_version }}-linux-x64.rpm
  ignore_errors: "{{ ansible_check_mode }}"

- name: RedHat/Centos | Removing Openjdk 1.8.0
  yum:
    name: java-1.8.0-openjdk
    state: absent
  when: openjdk == 1

- name: RedHat/Centos | Installing Java 8
  yum:
    name: "/opt/jdk-{{ jre_version }}-linux-x64.rpm"
    state: installed
  register: java_8_installed
  ignore_errors: "{{ ansible_check_mode }}"

- name: Remove Java 8 SDK rpm
  file:
    path: "/opt/jdk-{{ jre_version }}-linux-x64.rpm"
    state: absent
  when: java_8_installed|success
  ignore_errors: "{{ ansible_check_mode }}"
