---

##########
# Nginx configuration
# Note: Update worker_processes to match the CPU core's found on the LB VMs.
nginx_setup:
  worker_processes: 1
  nginx_setup.worker_connections: 1024

#########
# Zabbix proxy settings
zabbix_proxy_name: zabbix-proxy
zabbix_proxy_local_buffer: 24
zabbix_proxy_offline_buffer: 72
zabbix_proxy_heartbeat: 60
zabbix_proxy_config_frequency: 3600
zabbix_proxy_sender_frequency: 60

##########
# Zabbix configuration
zabbix_web_user: nginx
zabbix_web_group: nginx
zabbix_web_package: zabbix-web-pgsql
zabbix_web_conf_dir: /etc/zabbix
zabbix_web_log_dir: /opt/data/zabbix/log/zabbix-web
zabbix_web_home_dir: /opt/data/zabbix/www/zabbix
zabbix_web_public_dir: /usr/share/zabbix
zabbix_server_host: "{{ hostvars[groups['zabbix-app'][0]]['ansible_ssh_host'] }}"
zabbix_server_port: 10051
zabbix_web_fqdn: MGTOPSSHSZABX01
logstash_conf_dir: /etc/logstash/conf.d
php_fpm_conf_dir: /etc/php-fpm.d/
zabbix_web_fastcgi_params: fastcgi_params

zabbix_repo_url: "http://repo.zabbix.com/zabbix/3.0/rhel/7/$basearch/"
zabbix_repo_enable: yes
zabbix_repo_gpgcheck: 1
zabbix_repo_gpg_url: "http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX"
zabbix_yum_packages:
    - libselinux-python
    - zabbix-server-pgsql
    - zabbix-web-pgsql
    - zabbix-agent
    - zabbix-java-gateway
    - python-pyzabbix
    - nginx
zabbix_php_packages:
    - php
    - php-cli
    - php-common
    - php-devel
    - php-pear
    - php-gd
    - php-fpm
    - php-mbstring
    - php-ldap
    - php-pgsql
    - php-xml
