---

- name: Setup elasticsearch repo
  yum_repository:
    name: elasticsearch
    description: Elasticsearch repository
    baseurl: "{{ elastic_yum_url }}"
    gpgcheck: "{{ elasic_yum_check }}"
    gpgkey: "{{ elastic_yum_gpg }}"
    enabled: yes

- name: Install elasticsearch
  yum:
    name: elasticsearch
    state: installed

- name: Ensure elasticsearch is started on boot
  service:
    name: elasticsearch
    enabled: yes
