
- name: install zabbix agent
  yum:
    name: zabbix-agent
    state: latest

- name: Configure zabbix file
  template:
    src: zabbix-agent.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify:
    - restart zabbix-agent

- name: Ensure zabbix-agent is started and enabled on boot
  service:
    name: zabbix-agent
    state: started
    enabled: yes
