---

# Make sure service is started
- name: Starting Service
  service:
    name: "postgresql-{{ postgres_version_nr }}"
    state: started
  ignore_errors: "{{ ansible_check_mode }}"

- name: Configure postgres user
  postgresql_user:
    db: postgres
    name: postgres
    password: postgres
    role_attr_flags: SUPERUSER
  become_user: postgres
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create project database users
  become_user: postgres
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
  with_items:
    - "{{ postgres_project_users }}"
  when: postgres_project_users is defined
  ignore_errors: "{{ ansible_check_mode }}"

- name: create project databases
  become_user: postgres
  postgresql_db:
    name: "{{ item.name }}"
    encoding: "'{{ item.encoding }}'"
    #lc_collate: "'{{ item.locale }}'"
    #lc_ctype: "'{{ item.locale }}'"
    #template: "'template0'"
    owner: "{{ item.owner | default('postgres') }}"
  with_items:
    - "{{ postgres_project_database }}"
  when: postgres_project_database is defined
  ignore_errors: "{{ ansible_check_mode }}"

- name: Add hba file
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgres_data_directory }}/data/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0600
  notify:
    - restart postgres
  ignore_errors: "{{ ansible_check_mode }}"

- name: Add postgres file
  template:
     src: postgresql.conf.master.j2
     dest: "{{ postgres_data_directory }}/data/postgresql.conf"
     owner: postgres
     group: postgres
     mode: 0600
  notify:
    - restart postgres
  ignore_errors: "{{ ansible_check_mode }}"
