# Run script to create a new  database.
- name: Add database creation script to server.
  template:
     src: setup_database.sql.j2
     dest: "/tmp/setup_database.sql"
     owner: postgres
     group: postgres
     mode: 600
     backup: yes
  when: run_postgres_creation_script is defined

# Run script to create a new  database.
- name: Create database
  command: 'su - postgres -c "psql -U postgres -f /tmp/setup_database.sql"'
  register: psql_result
  failed_when:
    psql_result.rc != 0 and ("already exists" not in psql_result.stderr)
  changed_when: "psql_result.rc == 0"
  when: run_postgres_creation_script is defined
