---

- name: Copy files to Postgres location
  copy:
    src: "create/{{ item }}"
    dest: "{{ postgres_data_directory }}/{{ item }}"
    owner: postgres
    group: postgres
    mode: 0644
  with_items:
    - data.sql
    - images.sql
    - schema.sql
  
